### ISSUE TITLE
Bug: /settings API doesnt include / merge settings from local.yaml

### ISSUE THREAD

**Issue by marekmru** [plan-net/core4#81]
core4.yaml
user_setting:
   _general:
     language: EN

local.yaml
user_setting:
  _general:
     menu:
       Imprint: /home4/menu/imprint
       Privacy Policy: /home4/menu/pp

should result in:
user_setting:
   _general:
     language: EN
     menu:
       Imprint: /home4/menu/imprint
       Privacy Policy: /home4/menu/pp

**Comment by m-rau** [comment]
I am gonna have a look into that

**Comment by m-rau** [comment]
The configuration mechanic is as expected:
* keys in ``core4.yaml`` can be overwritten
* keys in ``core4.yaml`` cannot be extended

For this reason, the above scenario does not work. Example:
```
user_setting:
   _general:
     language: UK
     menu:
       k1: /v1
       k2: /v2
```
This configuration in ``core4.yaml`` allows the keys ``k1`` and ``k2`` to be overwritten. All additional keys in ``menu`` are ignored because they are considered *out-of-scope*.

This is the reason why it appears, that the elements of ``menu`` are not merged.

## solution

Define the value type of ``menu`` as an list. This list can then be overwritten in ``local.yaml``. Please note, that still the keys are not merged. This is intended behavior. The value of key ``menu`` are replaced:

example:
```
user_setting:
   _general:
     language: EN
     menu:
       - About: /about
```
can be extended in ``local.yaml`` by:
```
user_setting:
   _general:
     language: EN
     menu:
       - About: /about
       - Help Me: /help
```
The advantage of a *list* type is, that the menu order can be specified.

# action required
* refactor menu setting in ``core4.yaml``
* refactor the custom  navigation (#73) to handle list
* close this ticket
